version: '3.4'

services:
  chefrecipes.api.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5054
      - ASPNETCORE_HTTPS_PORTS=5055
    ports:
      - "5054:5054"
      - "5055:5055"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro